title: Aleph Personal Library
description: "The goal is not to read books. It is to interconnect them. A living graph of ideas for iOS."
author: Diego Zárate Rosales
url: "https://alephlibrary.com"
baseurl: ""  # Debe quedar absolutamente vacío si usas un dominio TLD.
permalink: /:title/
markdown: kramdown
timezone: America/Puerto_Rico
exclude:
  - README.md
  - .gitignore
